export {
  type AttributeSpec,
  type Attrs,
  ContentMatch,
  type DOMOutputSpec,
  DOMParser,
  DOMSerializer,
  Fragment,
  type MarkSpec,
  type NodeSpec,
  type ParseOptions,
  type ParseRule,
  Mark as PMMark,
  MarkType as PMMarkType,
  Node as PMNode,
  NodeRange as PMNodeRange,
  NodeType as PMNodeType,
  ReplaceError,
  ResolvedPos,
  Schema,
  type SchemaSpec,
  Slice,
} from "@tiptap/pm/model";
export {
  AllSelection,
  EditorState,
  NodeSelection,
  type Command as PMCommand,
  type EditorStateConfig as PMEditorStateConfig,
  Plugin as PMPlugin,
  PluginKey as PMPluginKey,
  type PluginSpec as PMPluginSpec,
  type PluginView as PMPluginView,
  type SelectionBookmark as PMSelectionBookmark,
  type StateField as PMStateField,
  Selection,
  SelectionRange,
  TextSelection,
  Transaction,
} from "@tiptap/pm/state";
export {
  AddMarkStep,
  AddNodeMarkStep,
  AttrStep,
  canJoin,
  canSplit,
  DocAttrStep,
  dropPoint,
  findWrapping,
  insertPoint,
  joinPoint,
  liftTarget,
  type Mappable,
  Mapping,
  MapResult,
  RemoveMarkStep,
  RemoveNodeMarkStep,
  ReplaceAroundStep,
  ReplaceStep,
  replaceStep,
  Step,
  StepMap,
  StepResult,
  Transform,
} from "@tiptap/pm/transform";
export {
  Decoration,
  type DecorationAttrs,
  DecorationSet,
  type DecorationSource,
  type DirectEditorProps as PMDirectEditorProps,
  type DOMEventMap as PMDOMEventMap,
  type EditorProps as PMEditorProps,
  EditorView as PMEditorView,
  type MarkViewConstructor as PMMarkViewConstructor,
  type NodeView as PMNodeView,
  type NodeViewConstructor as PMNodeViewConstructor,
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-expect-error
  __serializeForClipboard as serializeForClipboard,
} from "@tiptap/pm/view";
